"""initial migration

Revision ID: 2ffc547375a0
Revises: None
Create Date: 2015-04-04 14:40:34.968851

"""

# revision identifiers, used by Alembic.
revision = '2ffc547375a0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
